### ISSUE TITLE
[Feature Request] DEB package

### ISSUE THREAD

**Issue by gsbhasin123** [UberWriter/uberwriter#189]
can we please have a deb package for ubuntu/debian or a ppa?

**Comment by wolfv** [comment]
In my experience, debian packaging is really painful. I would be more curious if we can easily make a `.snap` package as an alternative to the flatpak, but personally I don't think I can spend much time on this. Maybe you can give it a shot yourself @gsbhasin123 ?

**Comment by gsbhasin123** [comment]
Actually, I'd be more than happy to once I learn how to compile UberWriter!

I'm a little busy right now, but I think I can find some time in the next few days. Also as to snap packages, in my experience flatpaks work better. or AppImages - they're the best cross-platform software distrobution tool objectively because they work on any distro without needing to install anything :P

**Comment by somas95** [comment]
I don't know how easy would that be, @wolfv, specially if at some point we implement portals (and we should, at least for the file chooser). I can understand why someone would want a "native" package instead of a sandboxed one, but supporting two different universal/sandboxed packages seems counterproductive.
In any case packagers are free to package whatever they want, but I don't have the resources nor knowledge to make a .deb either.

P.s, doesn't ubuntu/debian support flatpak? I know for sure elementary Os does (they moved from snap too)

**Comment by somas95** [comment]
@gsbhasin123 yeah, I like that from AppImages, but from a technical point of view they're way worse (they don't integrate with the system, you cannot update them, they're not sandboxed, etc etc...)

For compiling, just follow https://github.com/UberWriter/uberwriter#building-from-git
It's way easier to compile it now than it was used to be since we migrated everything to meson

**Comment by gsbhasin123** [comment]
@somas95 AppImages can do a lot with AppImageLauncher, but that's not the point here :package:  I know a little about debian packaging, I'll try.

**Comment by gsbhasin123** [comment]
Hm I can't even get it to compile!
```
Traceback (most recent call last):
  File "/usr/bin/uberwriter", line 44, in <module>
    import uberwriter
ModuleNotFoundError: No module named 'uberwriter'
```
After a clean compilation with no errors, running uberwriter in a Terminal shows that. Any suggestions? Once I get this working, the deb package should be a breeze!

**Comment by somas95** [comment]
Hmmmm....
I'm gonna try to compile it in a VM, I've never seen that before

**Comment by wolfv** [comment]
maybe uberwriter was installed globally before?

**Comment by somas95** [comment]
It's not that. Seems that we don't put uberwriter on the path. I'll take a look at it later

**Comment by gsbhasin123** [comment]
Note that I did do the commented out Ninja command to install globally

**Comment by somas95** [comment]
it's not commented, it's just a common convention to indicate sudo commands:

```bash
$ regular command
# sudo command
```

**Comment by gsbhasin123** [comment]
Ah, I see. If someone was copy pasting they might think it's commented. Usually, # is used for a root prompt, while $ is used for a normal prompt when using `sudo`. The command in question was `sudo ninja -C builddir install`. Am I doing everything correctly?

**Comment by gsbhasin123** [comment]
Any update on why it isn't compiling? I'm eager to get a proper .deb working :p

**Comment by somas95** [comment]
Sorry, holidays were some busy days. I'm quite sure that the issue is we are not putting in the path uberwriter's directory (see https://github.com/UberWriter/uberwriter/blob/0d1da19ce8fe013b5abd6b227fbadc00f2d72b8c/uberwriter.in#L34)

I'll try to fix it when I return home

**Comment by gsbhasin123** [comment]
Okay I see.
Thanks so much!!

**Comment by gsbhasin123** [comment]
@somas95 I switched to a Conda installation of Python. Instead of that issue, I now am getting
```
Traceback (most recent call last):
  File "/usr/bin/uberwriter", line 28, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'


```
Even though `pgi` and `pygobject` packages are installed.

**Comment by somas95** [comment]
If you're using conda, did you install pygobject with conda too?
Python installations get really funny 

![obligatory xkcd](https://imgs.xkcd.com/comics/python_environment.png)

**Comment by gsbhasin123** [comment]
Yes I installed both pgi and pygobject *with Conda*. however note the normal python3 (`/usr/bin/python3`) is still throwing that error.

**Comment by gsbhasin123** [comment]
Any update? :/

**Comment by somas95** [comment]
I've been busy with the finals (you know university and January...), but Wednesday I should be able to take a look at this. 

In any case: pgi is not needed, I'd uninstall it. Be sure you have the correct version of pygobject. I'd try to install it from the repos, not conda, but as I said, be aware that previous versions for python2 etc are there

**Comment by gsbhasin123** [comment]
:/ too many pythons

**Comment by sten0** [comment]
@gsbhasin123, are you already involved in Debian?  I started working on the Debian package two days ago, found this [RFP bug] (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721192) today, took responsibility, got it to build, and now I'm doing the copyright review. @wolfv @somas95, I'll file separate issues for those, since they're ftpmaster autoreject things.

**Comment by sten0** [comment]
P.S. @wolfv @somas95 the process will go a bit faster if you would let me know what vendored copies of the libraries have been modified enough that I can no longer unbundle them.  eg: I think this is the case for latex2png, and this is why I recognise your names :-)

**Comment by gsbhasin123** [comment]
@sten0 No I'm not-I'm an ubuntu user :p

**Comment by sten0** [comment]
Gurjus Bhasin <notifications@github.com> writes:

> @sten0 No I'm not-I'm an ubuntu user :p 
>

:-) If the package isn't completed+accepted into Debian and
installed to the archive before 27 February 2020, then it won't make it
into Ubuntu's 20.04, but--if I understand correctly--it's already
available in the Ubuntu store?  I'm not able to confirm for Ubuntu, but
Pop! OS 19.10 doesn't have it.

P.S. of course anyone is welcome to take the eventual Debian source
package--the dsc, orig.tarball, and debian.tarball, ex: dget $URL--and
start a PPA.
